### ISSUE TITLE
Running runARCSdemo.sh - IOError: [Errno 2] No such file or directory: 'hsapiens-8reformat.fa.scaff_s98_c5_l0_d0_e30000_r0.05_original.gv'

### ISSUE THREAD

**Issue by rafaeltiveron** [bcgsc/arcs#31]
After I installed ARCS, I tryed to test example data:

```
root@user-lubuntu:/mnt/hgfs/SharedFolders/programas/arcs/Examples/arcs_test-demo# ./runARCSdemo.sh
Downloading sample Chromium read alignment .bam file and human genome assembly draft...
--2018-04-28 23:37:55--  ftp://ftp.bcgsc.ca/supplementary/ARCS/testdata/NA24143_genome_phased_namesorted.bam1.sorted.bam
           => “NA24143_genome_phased_namesorted.bam1.sorted.bam”
Resolvendo ftp.bcgsc.ca (ftp.bcgsc.ca)... 134.87.4.91
Conectando-se a ftp.bcgsc.ca (ftp.bcgsc.ca)|134.87.4.91|:21... conectado.
Acessando como anonymous ... Acesso autorizado!
==> SYST ... feito.    ==> PWD ... feito.
==> TYPE I ... feito.  ==> CWD (1) /supplementary/ARCS/testdata ... feito.
==> SIZE NA24143_genome_phased_namesorted.bam1.sorted.bam ... 23218461706
==> PASV ... feito.    ==> RETR NA24143_genome_phased_namesorted.bam1.sorted.bam ... feito.
Tamanho: 23218461706 (22G) (não autoritário)

NA24143_genome_phased_name  40%[===============>                        ]   8,69G  --.-KB/s    in 4h 33m

2018-04-29 04:11:19 (556 KB/s) - Conexão de dados: Tempo esgotado para conexão; A conexão de controle está fechada.
Tentando novamente.

--2018-04-29 04:26:20--  ftp://ftp.bcgsc.ca/supplementary/ARCS/testdata/NA24143_genome_phased_namesorted.bam1.sorted.bam
  (tentativa: 2) => “NA24143_genome_phased_namesorted.bam1.sorted.bam”
Conectando-se a ftp.bcgsc.ca (ftp.bcgsc.ca)|134.87.4.91|:21... conectado.
Acessando como anonymous ... Acesso autorizado!
==> SYST ... feito.    ==> PWD ... feito.
==> TYPE I ... feito.  ==> CWD (1) /supplementary/ARCS/testdata ... feito.
==> SIZE NA24143_genome_phased_namesorted.bam1.sorted.bam ... 23218461706
==> PASV ... feito.    ==> REST 9335154088 ... feito.
==> RETR NA24143_genome_phased_namesorted.bam1.sorted.bam ... feito.
Tamanho: 23218461706 (22G), 13883307618 (13G) restantes (não autoritário)

NA24143_genome_phased_name 100%[++++++++++++++++=======================>]  21,62G   752KB/s    in 5h 47m

2018-04-29 10:13:43 (651 KB/s) - A conexão de controle está fechada.
Tentando novamente.

--2018-04-29 10:28:45--  ftp://ftp.bcgsc.ca/supplementary/ARCS/testdata/NA24143_genome_phased_namesorted.bam1.sorted.bam
  (tentativa: 3) => “NA24143_genome_phased_namesorted.bam1.sorted.bam”
Conectando-se a ftp.bcgsc.ca (ftp.bcgsc.ca)|134.87.4.91|:21... conectado.
Acessando como anonymous ... Acesso autorizado!
==> SYST ... feito.    ==> PWD ... feito.
==> TYPE I ... feito.  ==> CWD (1) /supplementary/ARCS/testdata ... feito.
==> SIZE NA24143_genome_phased_namesorted.bam1.sorted.bam ... 23218461706
O arquivo já foi obtido.
2018-04-29 10:28:47 (0,00 B/s) - “NA24143_genome_phased_namesorted.bam1.sorted.bam” salvo [23218461706]

--2018-04-29 10:28:47--  ftp://ftp.bcgsc.ca/supplementary/ARCS/testdata/hsapiens-8reformat.fa
           => “hsapiens-8reformat.fa”
Resolvendo ftp.bcgsc.ca (ftp.bcgsc.ca)... 134.87.4.91
Conectando-se a ftp.bcgsc.ca (ftp.bcgsc.ca)|134.87.4.91|:21... conectado.
Acessando como anonymous ... Acesso autorizado!
==> SYST ... feito.    ==> PWD ... feito.
==> TYPE I ... feito.  ==> CWD (1) /supplementary/ARCS/testdata ... feito.
==> SIZE hsapiens-8reformat.fa ... 3074865858
==> PASV ... feito.    ==> RETR hsapiens-8reformat.fa ... feito.
Tamanho: 3074865858 (2,9G) (não autoritário)

hsapiens-8reformat.fa      100%[=======================================>]   2,86G   459KB/s    in 86m 58s

2018-04-29 11:55:48 (575 KB/s) - “hsapiens-8reformat.fa” salvo [3074865858]

Running ARCS...
Converting graph for LINKS...
Traceback (most recent call last):
  File "./makeTSVfile.py", line 96, in <module>
    readGraphFile(infile)
  File "./makeTSVfile.py", line 15, in readGraphFile
    with open(infile, 'r') as f:
IOError: [Errno 2] No such file or directory: 'hsapiens-8reformat.fa.scaff_s98_c5_l0_d0_e30000_r0.05_original.gv'
Running LINKS...
run complete
```

**Comment by warrenlr** [comment]
Oi,

Looks like you had a connection timeout downloading the alignment .BAM file:

Conexão de dados: 
Tempo esgotado para conexão; A conexão de controle está fechada.
Tentando novament

Without linked-read alignment files, the rest of the pipeline can not proceed as intended. In your second attempt, it is possible that the complete download had a .1 appended. I suggest removing all downloaded files and trying again.  Good luck.

Obrigado,
Rene

**Comment by rafaeltiveron** [comment]
Thanks warrenlr for the comment. It seems not the case. I've checked the files and are not corrupted. I've almost untangled the problem, which is inside "ARCS.sh". The argument "-v 1" seems not needing "1", so I deleted them. Now, arcs are running correctly. Let see if LINKS are gonna run rightly, them if any new problem, I'll post here. Thank you

**Comment by rafaeltiveron** [comment]
Oh, yes. That worked! The final file is the same as generated before on the example.

**Comment by warrenlr** [comment]
excellent! glad it works :)
